### ISSUE TITLE
Various known issues

### ISSUE THREAD

**Issue by Lolibox** [Sigmmma/c20#60] opened 2020-09-18 22:02 UTC
While contributing to Refined and working on Enhanced mod projects I started to keep a log of different issues with the Gearbox port of the game, ranging from engine specific to renderer and api issues. Noted behaviors and solutions/workarounds.

I've attempted to organize them into categories. Some of these might already be in the wiki, i havent had the chance to browse through the whole thing yet.

Renderer
Issues related to how the game renders shaders and effects.
-Fog screen layers effect does not render at all. All fog contains information in this section for a simulated volumetric fog (only working in the Xbox version, also might be broken in backward compat modes. need more confirmation). *not the same thing as sky fog (atmospheric fog)*
-Shield meters missing flash effect when drained, the end of the meter is brightened by a white gradient (only working in the Xbox version).
-Texture assets dont load immediately. Pillar of Autumn thruster lens flares for example, or plasma decals. Easiest way to see this is to load the pillar of autumn opening cutscene for the first time on game load, the thrusters almost dont show up at all in the time they are in view of the camera (only Custom Edition?).
-Detail after reflection flag is working in reverse of what it should. the flag changes the order the detail is applied as a toggle, detail after reflection marked should apply detail over specular/cubemap. (only working correctly in the Xbox version, Chimera has a built-in fix which is disabled for CE in the main builds)
-Environment shaders on objects do not function properly. Specularity isn't masked (only working on xbox), atmospheric fog also does not render correctly on objects that use environment shaders (only broken in CE).
-Bitmap types not normally supported without mods: all monochrome formats and p8 bumpmaps. these formats are high quality and save on space being channel limited (Xbox version supports these, Chimera supports them or used to).
-Various blend modes for shaders are broken. Multiply in transparent shaders, double multiply in decals and render invisibly (Decals work properly in MCC, decals also work with chimera now).
-Shader environment "normal" type wrongly masks primary and secondary detail maps when an alpha is present in the base map. See b40 exterior tech wall <<< my hypothesis for now (working on Xbox only).
-Shader environment does not tint cubemaps with the bumped cubemap reflection type, perp/para brightness does not work correctly either under bumped reflection with both just being a general scale instead of on angle. I believe some specular light is missing as well which makes dynamic lights appear a smaller radius (flashlight). Bumpmap shadows do not render on environment shaders from using lightmap/bsp info. (only working on the original xbox version)
-Weather particles dont draw near opaque fog, seems to be more transparency sorting problems, need a proper source but i believe it should either fade when the fog plane does or show up through the entire volume.
-Atmospheric fog appears to have sorting issues with fog volumes(planes), and is even further compounded by water shader sorting... see c10(guilty spark) swamp water/fog rendering its an absolute mess. the water sorting issues seem to have been fixed with MCC along with the mipmapping.

API
Issues related to how shader code is handled by the API on different hardware.
-Mirror surfaces don't reflect properly. light volumes/projectiles are offset. (only working in the MCC and Xbox version of the game).
-Water shader renders improperly in the Gearbox versions of the game. Mipmapping appears to be working in reverse. volume fog and atmospheric fog both seem to sort badly through both sides (working in MCC and Xbox versions).
-Glass shaders require mods to work in the Gearbox version of the game (Retail/Trial only). The same mods do not work for Custom edition (working in MCC and Xbox versions, CE needs a shader workaround)
-Environment shader self illumination animation has inconsistent behavior. Plasma animation does not scale or loop properly on some hardware (working in MCC/Xbox).
-Plasma shader has inconsistent behavior between different hardware. The wrong behavior is the default in MCC (only working in the Xbox version. Apparently MCC doesnt use 3d textures for this, i dont have an accurate source just hearsay).
-Some processors/gpus cause problems with the renderer, specifically transparent shaders stretching/exploding, and mirror reflections exploding (must force 1 core affinity in the game process)

Engine
Issues related to the way the engine handles certain features.
-Camera point animation stops being smooth at framerates over 60.
-Widescreen aspect ratios and FOV's over the default show normally offscreen garbage such as objects popping in and out of creation (Chimera has a cinematic FOV option to fix this, and will eventually get a pillarbox feature).
-First person models clip through geometry while active camo is in effect, something something clipping planes? (may or may not be fixable with mods).
-Transparent shaders occasionally Zfight with bsp geometry due to floating point precision (may or may not be fixable with mods).
-Contrail point generation tied to fps. Higher than 30 fps causes contrails to bunch up and twist, and animate faster (fixed with mods like chimera).
-No control over the quality of fonts, resolution and size are linked and tool rasterizes fonts automatically (chimera now has a high quality font feature to replace ingame fonts).
-UI bitmaps/widgets have some hard limits on resolution and resolution and size on screen are directly linked, you can work around it somewhat by using negative bounds values in the widget to scale a bitmap down. this doesnt really seem to work for widgets that are heavily cropped by bounds already.
-Transparent shaders do not sort properly behind Glass shaders, they will shift in front and behind each other. part indexes allow draw order to be set manually for objects through gbxmodel, there is no such method for bsps, the best you can do is flag the transparent shader to "draw before water". glass shaders seem to render in the same position as water.
-Dynamic shadows are at a fixed resolution/quality (may or may not be a way to change this with mods in the future)
-Weapon fire rates are rounded for values not divisors of 30, has to do with time and tick rates and 30 is the maximum fire rate.
-Camera shake in damage_effects tied to framerate, short duration shakes (0.05) get skipped occasionally at high fps (fixed and interpolated by chimera).
-Rounds between tracers should apply per projectile and not per shot, weapons like the banshee/ghost and shade turret do not work the same as their xbox counterparts.
-Radar blip ghosting effect/fading scaled by FPS. (Fixed with Chimera)
-Several debug and console commands are present ingame for PC but do not work or are disabled, and many of them work in sapien. it appears they do work in xbox builds of the game, mostly commands that draw to the screen such as debug_objects.

Editing Kit
Issues related to how the editing kit works with the HEK release
-Transparent shaders with extra layers will crash sapien when using the "transparent self occlusion" flag in object properties. Same shader will work completely fine ingame. Seems to be more of a warning, possibly for performance that is just enforced this way.
-Sapien debug wireframe colors change at angles. Hard to identify types of info when everything just turns black.
-Sapien game window is at a fixed resolution and aspect ratio.

MISC
Quirks or random tidbits/notes
-Transparent chicago shaders inherit parent properties if referenced as an extra shader layer, ie: first map type cubemap reflection flag will make the first map type for the child shader also a cubemap regardless of its own flags
-Transparent chicago extended shaders have an additional block used for fixed function rendering that uses less map stages.
-PC version of the game seems to be an earlier version of the engine pre-retail xbox release as evident by missing features, an incomplete renderer and beta assets.
-Some tags are changed by tool depending on scenario type for balancing in campaign (plasma rifle and pistol)
-cannot unmerge scenarios/extract child scenarios from maps, source tags needed and we dont have access to them. this causes things like duplicate camera points and infamously the garbage collection spam for c10 in sapien.

**Comment by csauve** [comment] 2020-09-19 07:04
I've started incorporating these notes. First PR up: https://github.com/Sigmmma/c20/pull/61

**Comment by csauve** [comment] 2020-09-21 06:47
Continued work in https://github.com/Sigmmma/c20/pull/62

**Comment by csauve** [comment] 2020-09-26 23:06
The final PR is up here:
https://github.com/Sigmmma/c20/pull/65

There were some things which didn't make the cut for various reasons:

## Future work
There were a few tips regarding scripting and weapon fire rates which have been noted but will be included when I later give those sections of the site more attention. Scripting and weapons are bigger topics than I wanted to get into at the moment.

## Couldn't reproduce
* A report that various framebuffer blend modes for shaders and decals are broken, specifically double-multiply when not using Chimera, could not be verified. Decals were rendering properly on a vanilla Halo for me.
* A report that texture assets don't load immediately (e.g. thruster flares in a10 intro) could not be verified; the effect appeared as intended immediately when playing this map after game launch.

## Not notable enough
There were a few notes around FP models clipping while in active camo, widescreen showing things offscreen during cinematics, and dynamic shadows being fixed resolution that I didn't think were notable enough for the wiki so left out.

**Closed** 2020-10-04 07:00 UTC
