### ISSUE TITLE
git lfs tracking non-media files

### ISSUE THREAD

**Issue by Pepper-Man** [Sigmmma/c20#168] opened 2022-05-11 13:55 UTC
Title is pretty self explanatory

I'm not a seasoned git/github user but I know the basics
After installing git lfs and cloning the project to my local machine, any normal git commit/push i make to my github repo results in new .MD files being lfs tracked, and not displaying on github properly

**Comment by num0005** [comment] 2022-05-11 17:35
Closing this as it appears to have been caused by accidentally tracking all files with LFS.

**Closed by num0005** 2022-05-11 17:35 UTC
Labels: bug, build, invalid
